backend:
  name: github
  repo: BRITorg/decap_eval
  branch: main
  base_url: https://decap-eval-oauth.jbest.workers.dev

media_folder: content/images
public_folder: /content/images

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
